[package]
name = "gantz_store"
version = "0.1.0"
description = "Storage of the gantz registry over key-value stores."
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license = "MIT OR Apache-2.0"
repository.workspace = true

[dependencies]
base64.workspace = true
bevy_pkv = { workspace = true, optional = true }
gantz_ca.workspace = true
ron.workspace = true
serde.workspace = true
tracing.workspace = true

[features]
# `Load` and `Save` for `bevy_pkv::PkvStore`.
pkv = ["dep:bevy_pkv"]
