[package]
name = "gantz_pattern"
version = "0.1.0"
description = "A pattern domain for gantz, implemented as a Steel module."
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license = "GPL-3.0-or-later"
repository.workspace = true

[dependencies]
gantz_core.workspace = true
